"""Remove unique constraint on mobile_number

Revision ID: 3bb92709766e
Revises: 006_add_notifications_table
Create Date: 2026-08-17 18:02:36.036611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bb92709766e'
down_revision: Union[str, Sequence[str], None] = '006_add_notifications_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('youtube_url', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('youtube_video_id', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('video_title', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_documents_youtube_url'), 'documents', ['youtube_url'], unique=False)
    op.create_index(op.f('ix_documents_youtube_video_id'), 'documents', ['youtube_video_id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=False)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_documents_youtube_video_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_youtube_url'), table_name='documents')
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'video_title')
    op.drop_column('documents', 'youtube_video_id')
    op.drop_column('documents', 'youtube_url')
    # ### end Alembic commands ###
